##№1

 Импортируйте библиотеку Numpy и дайте ей псевдоним np. Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй — числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец — это признак, а строка — наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [4]:
import numpy as np

In [160]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])
T = a.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [157]:
numpy.mean(T[0])

2.0

In [158]:
numpy.mean(T[1])

8.4

In [161]:
mean_a = np.array([numpy.mean(T[0]),numpy.mean(T[1])])
mean_a

array([2. , 8.4])

##№2

Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [162]:
a_centered = np.array([T[0]-mean_a[0],T[1]-mean_a[1]])
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

##№3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N — число наблюдений.

In [163]:
a_centered_sp = 0
for i in range(5):
    a_centered_sp += a_centered[0,i] * a_centered[1,i] 
a_centered_sp

8.0

In [385]:
N = len(a)

In [386]:
a_centered_sp/(N-1)

2.0

##№4

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом — с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив a. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [387]:
np.cov(a.T)[0,1]


2.0

##№5

 Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

In [388]:
import pandas as pd

In [389]:
authors = pd.DataFrame({"author_id": [1, 2, 3],
                       "author_name":['Тургенев', 'Чехов', 'Островский']}, columns = ["author_id","author_name"])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные: [1, 1, 1, 2, 2, 3, 3], ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], [450, 300, 350, 500, 450, 370, 290].

In [390]:
books = pd.DataFrame({"author_id": [1, 1, 1, 2, 2, 3, 3],
                    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    "price": [450, 300, 350, 500, 450, 370, 290]}, columns = ["author_id","book_title","price"])
books 

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

##№6

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [391]:
authors_price = pd.merge(authors,books,on = "author_id",how = "inner")
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

##№7

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [392]:
top5_1 = authors_price.sort_values(by ="price")
top5_1

author_id author_name            book_title  price
6          3  Островский  Таланты и поклонники    290
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
5          3  Островский                 Гроза    370
0          1    Тургенев           Отцы и дети    450
4          2       Чехов       Дама с собачкой    450
3          2       Чехов      Толстый и тонкий    500

In [393]:
top5_1 = top5_1.reset_index(drop = True)
top5_1

author_id author_name            book_title  price
0          3  Островский  Таланты и поклонники    290
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          3  Островский                 Гроза    370
4          1    Тургенев           Отцы и дети    450
5          2       Чехов       Дама с собачкой    450
6          2       Чехов      Толстый и тонкий    500

In [394]:
top5 = pd.DataFrame(top5_1.loc[2:6,"price"]).reset_index(drop = True)
top5 

price
0    350
1    370
2    450
3    450
4    500

##№8


Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца: author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [395]:
Turg =authors_price.loc[authors_price["author_name"].isin(['Тургенев']),:])
Turg.sort_values(by ="price").reset_index(drop = True)

SyntaxError: invalid syntax (<ipython-input-395-27616f80e372>, line 1)

In [396]:
min_price_T = Turg["price"].min()
max_price_T = Turg["price"].max() 
sredn_T=Turg["price"].mean()

In [397]:
Cheh = authors_price.loc[authors_price["author_name"].isin(['Чехов']),:]
Cheh.sort_values(by ="price").reset_index(drop = True)

author_id author_name        book_title  price
0          2       Чехов   Дама с собачкой    450
1          2       Чехов  Толстый и тонкий    500

In [398]:
min_price_Ch = Cheh["price"].min() 
max_price_Ch = Cheh["price"].max()
sredn_Ch = Cheh["price"].mean()

In [399]:
Ostr = authors_price.loc[authors_price["author_name"].isin(['Островский']),:]
Ostr.sort_values(by ="price").reset_index(drop = True)

author_id author_name            book_title  price
0          3  Островский  Таланты и поклонники    290
1          3  Островский                 Гроза    370

In [400]:
min_price_O = Ostr["price"].min() 
max_price_O = Ostr["price"].max()
sredn_O=Ostr["price"].mean()

In [401]:
authors_stat = pd.DataFrame({"author_name": ['Тургенев', 'Чехов', 'Островский'] ,
                    "min_price": [min_price_T,min_price_Ch,min_price_O],
                    "max_price": [max_price_T,max_price_Ch,max_price_O],
                            "mean_price": [sredn_T,sredn_Ch,sredn_O]
                            }, columns = ["author_name","min_price","max_price","mean_price"])
authors_stat

author_name  min_price  max_price  mean_price
0    Тургенев        300        450  366.666667
1       Чехов        450        500  475.000000
2  Островский        290        370  330.000000

##№9* - не сделала

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги — твердая или мягкая. В этот столбец поместите данные из следующего списка: ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

In [402]:
authors_price["cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

 Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.

In [403]:
 ?pd.pivot_table

Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться «твердая» и «мягкая», а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy. Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [404]:
table = pd.pivot_table(authors_price, values="price", index=["author_name"],columns=["cover"])
table

cover        мягкая  твердая
author_name                 
Островский    330.0      NaN
Тургенев      325.0    450.0
Чехов           NaN    475.0